version: '3.8'

services:
  ros2_gazebo:
    build: .
    container_name: cerise_digital_twin
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=waffle
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./shared:/shared
    command: >
      bash -c "
        ros2 run ros_tcp_endpoint default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0
      "
